{
 "title": "spark-operator",
 "time": { "from": "2024-10-03T10:30:11.932Z", "to": "2024-10-03T10:44:59.699Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Metrics Series Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Kube Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in kube_prod.* metrics. We only need kube_prod_container_status_running. Other kube_prod metrics should be dropped",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topK(20, count({__name__=~\"kube_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Node Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in node_.* metrics. We only need node_cpu_seconds_total in mode idle. Other metrics should be dropped",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": "topK(10, count({__name__=~\"node_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Kubelet Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in prometheus kubelet metrics. This should be 0 as we do not want to scrape any kubelet metrics",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "count({__name__=~\"kubelet_.*\"}) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Apiserver Metrics Series Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
     "targets": [
      {
       "expr": "topK(10, count({__name__=~\"apiserver_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Go Memstats Alloc ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Prometheus Go Memstats Heap Alloc ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Prometheus Resident Memory ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus Remote Storage ",
     "type": "timeseries",
     "description": "One minutes rate of prometheus_remote_storage_bytes_total",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_bytes_total [1m]) / 1024 ^ 2",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus TSDB Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "targets": [
      { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Prometheus TSDB Head Series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  { "title": "Spark Job Status on EKS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Running Driver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (namespace)(kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Running Driver",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  by (namespace) (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Running Executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (namespace)(kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Runnin Executor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  by (namespace) (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Total Running Spark Pod Driver + Executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"}) + sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Driver + Executor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"}) + sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Operator Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "spark_application_controller_adds enqueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(spark_application_controller_adds[1m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "avg(rate(spark_application_controller_adds[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "spark_application_controller_adds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(spark_application_controller_adds[1m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "spark_application_controller_work_duration_count dequeue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(spark_application_controller_work_duration_count [1m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "avg(rate(spark_application_controller_work_duration_count [1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "spark_application_controller_work_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(spark_application_controller_work_duration_count [1m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Spark Application Controller Latency",
   "type": "timeseries",
   "description": "Average time a task has to stay in workqueue before being processed",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spark_application_controller_latency_sum[1m])/rate(spark_application_controller_latency_count[1m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "avg(rate(spark_application_controller_latency_sum[1m])/rate(spark_application_controller_latency_count[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Spark Application Controller Task Process Time",
   "type": "timeseries",
   "description": "Average time is taken to process an item that is fetched from workqueue",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spark_application_controller_work_duration_sum [1m])/rate(spark_application_controller_work_duration_count [1m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "avg(rate(spark_application_controller_work_duration_sum [1m])/rate(spark_application_controller_work_duration_count [1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Spark Application Controller Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "spark_application_controller_depth",
     "legendFormat": "{{app_kubernetes_io_name}}"
    },
    {
     "expr": "avg(spark_application_controller_depth)",
     "legendFormat": "AVG"
    }
   ]
  },
  { "title": "Spark Application apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "apiserver_request_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_request_total{resource=\"sparkapplications\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "spark application API request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(verb, code, resource) (rate(apiserver_request_total{resource=\"sparkapplications\"}[1m]))",
     "legendFormat": "{{verb}} - {{code}}"
    }
   ]
  },
  {
   "title": "Spark Application Status at Locust Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }
  },
  {
   "title": "NEW (not yet submitted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "locust_new_spark_application_gauge",
     "legendFormat": "NEW Job Count"
    }
   ]
  },
  {
   "title": "SUBMITTED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 70 },
   "targets": [
    {
     "expr": "locust_submitted_spark_application_gauge",
     "legendFormat": "SUBMITTED Job Count"
    }
   ]
  },
  {
   "title": "RUNNING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "locust_running_spark_application_gauge",
     "legendFormat": "RUNNING Job Count"
    }
   ]
  },
  {
   "title": "SUCCEEDING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 78 },
   "targets": [
    {
     "expr": "locust_succeeding_spark_application_gauge",
     "legendFormat": "SUCCEEDING Job Count"
    }
   ]
  },
  {
   "title": "COMPLETED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "locust_completed_spark_application_gauge",
     "legendFormat": "COMPLETED Job Count"
    }
   ]
  },
  { "title": "Node usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Total CPU time consumed by node in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[$__rate_interval])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1 min cpu utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 95 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[1m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "max(apiserver_storage_objects{resource=\"nodes\"})",
     "legendFormat": "Node Count"
    }
   ]
  },
  { "title": "ConfigMaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "configmap count by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "count(kube_configmap_info{namespace=~\"spark-job.*\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(count(kube_configmap_info{namespace=~\"spark-job.*\"}) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locust metrics - Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locust Submit (success) Rate 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "increase(locust_spark_application_submit_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locust Submit Job Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_success_total{instance=\"ec2-instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Locust Submit (fail) Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "increase(locust_spark_application_submit_fail_total{instance=\"ec2-instance\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Locust Submit Job Fail Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 17 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_fail_total{instance=\"ec2-instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Locust Submit Job Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_gauge{instance=\"ec2-instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locust User Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 25 },
     "targets": [
      { "expr": "locust_concurrent_user", "legendFormat": "User Count" }
     ]
    }
   ]
  },
  {
   "title": "Spark Operator Metrics - Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 }
  },
  {
   "title": "(operator) Failed Spark Job Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "increase(spark_app_failure_count [1m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "（operator) Failed Spark Job Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
   "targets": [
    { "expr": "spark_app_failure_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
    { "expr": "sum(spark_app_failure_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(operator) Averge Failure Job Run Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(spark_app_failure_execution_time_microseconds_sum [1m]) / rate(spark_app_failure_execution_time_microseconds_count [1m]) ",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "(operator) Success Spark Application Per Minutes",
   "type": "timeseries",
   "description": "Number of spark application change to SUCCEEDING state",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "\nrate(spark_app_success_count[1m])*60",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "sum(rate(spark_app_success_count[1m])*60)",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "(operator) Success Spark Application Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 130 },
   "targets": [
    { "expr": "spark_app_success_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
    { "expr": "sum(spark_app_success_count)", "legendFormat": "sum" }
   ]
  },
  {
   "title": "(operator) Average Success Job Run Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(spark_app_success_execution_time_microseconds_sum [1m]) / rate(spark_app_success_execution_time_microseconds_count [1m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "(operator) Spark Application Count Increase Per Minute",
   "type": "timeseries",
   "description": "Number of newly added spark application",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 138 },
   "targets": [
    { "expr": "rate(spark_app_count[1m])*60", "legendFormat": "{{app_kubernetes_io_instance}}" },
    {
     "expr": "sum(rate(spark_app_count[1m])*60)",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "(operator) Spark Application Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 138 },
   "targets": [
    { "expr": "spark_app_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
    { "expr": "sum(spark_app_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(operator) Submit Spark Application Per Minute",
   "type": "timeseries",
   "description": "Number of spark application chnaged to SUBMITTED state",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "increase(spark_app_submit_count[1m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "sum(increase(spark_app_submit_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(operator) Submitted Spark Application Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 146 },
   "targets": [
    { "expr": "spark_app_submit_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
    { "expr": "sum(spark_app_submit_count)", "legendFormat": "SUM" }
   ]
  },
  {
   "title": "(operator) Running Spark Application Count",
   "type": "timeseries",
   "description": "Number of spark application changed to RUNNING state",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 154 },
   "targets": [
    { "expr": "spark_app_running_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
    { "expr": "sum(spark_app_running_count)", "legendFormat": "SUM" }
   ]
  },
  {
   "title": "Spark Operator Resident Memory Usage",
   "type": "timeseries",
   "description": "spark operator pod RSS memory",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_namespace=\"spark-operator\"} / 1024 ^ 3",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Spark Operator Pod CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"spark-operator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Application Start Latency by 1H avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(spark_app_start_latency_microseconds_sum[60m])/rate(spark_app_start_latency_microseconds_count[60m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Spark Application Start Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(spark_app_start_latency_microseconds_sum[5m])/rate(spark_app_start_latency_microseconds_count[5m])",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  }
 ]
}