# reduce noise in the logs, set loglevel to 0 for most verbose
logLevel: 0
# adjusted for large scale workload
resources:
  requests:
   cpu: '1'
   memory: 2Gi
  limits:
   cpu: '8'
   memory: 16Gi

nodeSelector:
  operational: "true"
# for large scale workload
clientConnection:
  burst: 200
  qps: 100