apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
  labels:
    app: locust
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      component: master
  template:
    metadata:
      labels:
        app: locust
        component: master
    spec:
      serviceAccountName: locust-spark-submitter
      containers:
      - name: locust
        image: locustio/locust:latest
        ports:
        - containerPort: 8089
          name: web
        - containerPort: 5557
          name: master-1
        - containerPort: 5558
          name: master-2
        env:
        - name: SPARK_JOB_NS_NUM
          value: "${SPARK_JOB_NS_NUM:-1}"
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing dependencies..."
          pip install kubernetes pyyaml
          
          echo "Checking dependency versions..."
          pip list | grep -E 'kubernetes|pyyaml'
          
          echo "Checking file paths..."
          ls -l /locust
          
          echo "Starting Locust Master..."
          locust -f /locust/locust-spark-submit.py --master --host=http://dummy --web-port=8089
        volumeMounts:
        - name: locust-scripts
          mountPath: /locust
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: locust-scripts
        configMap:
          name: spark-locust-scripts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
  labels:
    app: locust
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      component: worker
  template:
    metadata:
      labels:
        app: locust
        component: worker
    spec:
      serviceAccountName: locust-spark-submitter
      containers:
      - name: locust
        image: locustio/locust:latest
        env:
        - name: SPARK_JOB_NS_NUM
          value: "${SPARK_JOB_NS_NUM:-1}"
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing dependencies..."
          pip install kubernetes pyyaml
          
          echo "Checking dependency versions..."
          pip list | grep -E 'kubernetes|pyyaml'
          
          echo "Checking file paths..."
          ls -l /locust
          
          echo "Starting Locust Worker..."
          locust -f /locust/locust-spark-submit.py --worker --master-host=locust-master
        volumeMounts:
        - name: locust-scripts
          mountPath: /locust
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: locust-scripts
        configMap:
          name: spark-locust-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: locust
  labels:
    app: locust
    component: master
spec:
  ports:
  - port: 8089
    targetPort: web
    name: web-ui
  - port: 5557
    targetPort: master-1
    name: master-1
  - port: 5558
    targetPort: master-2
    name: master-2
  selector:
    app: locust
    component: master