controllerThreads: 30
nodeSelector: 
  operational: "true"
tolerations:
  - key: "dedicated"
    value: "operational"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: In
          values: 
          - "cluster-operational-provisioner"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: emr-containers.amazonaws.com/component
          operator: In
          values: 
          - "spark.operator"
      topologyKey: kubernetes.io/hostname
webhook:
  enable: true
  nodeSelector: 
    operational: "true"
  tolerations:
    - key: "dedicated"
      value: "operational"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/nodepool
            operator: In
            values: 
            - "cluster-operational-provisioner"
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: emr-containers.amazonaws.com/component
              operator: In
              values: 
              - "spark.operator"
          topologyKey: kubernetes.io/hostname