apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-job
  namespace: spark-job0
spec:
  type: Python
  mode: cluster
  image: "${EMR_IMAGE_URL}"
  imagePullPolicy: "IfNotPresent"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "s3://${BUCKET_NAME}/testing-code/custom-spark-pi.py"
  sparkVersion: ${SPARK_VERSION}
  timeToLiveSeconds: 30
  arguments:
    - "--min_run_time"
    - "500"
    - "--max_run_time"
    - "800"
    - "--partitions"
    - "10"
    - "--pause_ratio"
    - "0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    # initContainers:
    #   - name: volume-permission
    #    image: public.ecr.aws/y4g4v0z7/busybox
    #    command: ['sh', '-c', 'sleep 2']
    cores: 1
    memory: "512m"
    labels:
      version: ${SPARK_VERSION}
    serviceAccount: "spark-job-sa0"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    nodeSelector:

  executor:
    # initContainers:
    #   - name: volume-permission
    #     image: public.ecr.aws/y4g4v0z7/busybox
    #     command: ['sh', '-c', 'sleep 2']
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: ${SPARK_VERSION}
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    nodeSelector:

  hadoopConf:
    # EMRFS filesystem
    fs.s3.customAWSCredentialsProvider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
    fs.s3.impl: com.amazon.ws.emr.hadoop.fs.EmrFileSystem
    fs.AbstractFileSystem.s3.impl: org.apache.hadoop.fs.s3.EMRFSDelegate
    fs.s3.buffer.dir: /mnt/s3
    fs.s3.getObject.initialSocketTimeoutMilliseconds: "2000"
    mapreduce.fileoutputcommitter.algorithm.version.emr_internal_use_only.EmrFileSystem: "2"
    mapreduce.fileoutputcommitter.cleanup-failures.ignored.emr_internal_use_only.EmrFileSystem: "true"
  sparkConf:
    spark.executor.heartbeatInterval: 3000s
    spark.scheduler.maxRegisteredResourcesWaitingTime: 40s
    spark.network.timeout: 120000s
    # Required for EMR Runtime
    spark.driver.extraClassPath: /usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/usr/share/aws/hmclient/lib/aws-glue-datacatalog-spark-client.jar:/usr/share/java/Hive-JSON-Serde/hive-openx-serde.jar:/usr/share/aws/sagemaker-spark-sdk/lib/sagemaker-spark-sdk.jar:/home/hadoop/extrajars/*
    spark.driver.extraLibraryPath: /usr/lib/hadoop/lib/native:/usr/lib/hadoop-lzo/lib/native:/docker/usr/lib/hadoop/lib/native:/docker/usr/lib/hadoop-lzo/lib/native
    spark.executor.extraClassPath: /usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/*:/usr/share/aws/hmclient/lib/aws-glue-datacatalog-spark-client.jar:/usr/share/java/Hive-JSON-Serde/hive-openx-serde.jar:/usr/share/aws/sagemaker-spark-sdk/lib/sagemaker-spark-sdk.jar:/home/hadoop/extrajars/*
    spark.executor.extraLibraryPath: /usr/lib/hadoop/lib/native:/usr/lib/hadoop-lzo/lib/native:/docker/usr/lib/hadoop/lib/native:/docker/usr/lib/hadoop-lzo/lib/native