{
 "title": "spark-operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CNI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CNI Total IP / Assinged IP / Not assigned IP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 1 },
     "targets": [
      { "expr": "sum(awscni_total_ip_addresses)", "legendFormat": "CNI Total IP" },
      {
       "expr": "sum(awscni_assigned_ip_addresses)",
       "legendFormat": "Assigned IP"
      },
      {
       "expr": "sum(awscni_total_ip_addresses) - sum(awscni_assigned_ip_addresses)",
       "legendFormat": "Not Assigned IP"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Metrics Series Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Kube Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in kube_prod.* metrics. We only need kube_prod_container_status_running. Other kube_prod metrics should be dropped",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topK(20, count({__name__=~\"kube_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Node Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in node_.* metrics. We only need node_cpu_seconds_total in mode idle. Other metrics should be dropped",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 12 },
     "targets": [
      {
       "expr": "topK(10, count({__name__=~\"node_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Kublet Metrics Series Count",
     "type": "timeseries",
     "description": "Count of series in prometheus kubelet metrics. This should be 0 as we do not want to scrape any kubelet metrics",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "count({__name__=~\"kubelet_.*\"}) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Apiserver Metrics Series Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 20 },
     "targets": [
      {
       "expr": "topK(10, count({__name__=~\"apiserver_.*\"}) by (__name__))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Go Memstats Alloc ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Prometheus Go Memstats Heap Alloc ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "Prometheus Resident Memory ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus-kube-prometheus-prometheus\"} / 1024 ^ 3",
       "legendFormat": "{{endpoint}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus Remote Storage ",
     "type": "timeseries",
     "description": "One minutes rate of prometheus_remote_storage_bytes_total",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_bytes_total [1m]) / 1024 ^ 2",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus TSDB Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
     "targets": [
      { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Prometheus TSDB Head Series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 29 },
     "targets": [
      { "expr": "prometheus_tsdb_head_series", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Spark Job Status on EKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Driver",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (namespace)(kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Running Driver",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  by (namespace) (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Running Executor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (namespace)(kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Runnin Executor",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  by (namespace) (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum  (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "Total Running Spark Pod Driver + Executor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"}) + sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Running Spark Pods & Driver Exec Ratio",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"}) + sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": " sum (kube_pod_container_status_running{container=\"spark-kubernetes-executor\"})/sum (kube_pod_container_status_running{container=\"spark-kubernetes-driver\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark Operator Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "spark_application_controller_adds enqueue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(spark_application_controller_adds[1m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      },
      {
       "expr": "avg(rate(spark_application_controller_adds[1m]))",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "spark_application_controller_adds",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(spark_application_controller_adds[1m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "spark_application_controller_work_duration_count dequeue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(spark_application_controller_work_duration_count [1m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      },
      {
       "expr": "avg(rate(spark_application_controller_work_duration_count [1m]))",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "spark_application_controller_work_duration_count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(spark_application_controller_work_duration_count [1m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Spark Application Controller Latency",
     "type": "timeseries",
     "description": "Average time a task has to stay in workqueue before being processed",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(spark_application_controller_latency_sum[1m])/rate(spark_application_controller_latency_count[1m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      },
      {
       "expr": "avg(rate(spark_application_controller_latency_sum[1m])/rate(spark_application_controller_latency_count[1m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Spark Application Controller Task Process Time",
     "type": "timeseries",
     "description": "Average time is taken to process an item that is fetched from workqueue",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(spark_application_controller_work_duration_sum [1m])/rate(spark_application_controller_work_duration_count [1m])",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      },
      {
       "expr": "avg(rate(spark_application_controller_work_duration_sum [1m])/rate(spark_application_controller_work_duration_count [1m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Spark Application Controller Queue Depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "spark_application_controller_depth",
       "legendFormat": "{{app_kubernetes_io_name}}"
      },
      {
       "expr": "avg(spark_application_controller_depth)",
       "legendFormat": "AVG"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark Application apiserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "apiserver_request_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by(verb) (rate(apiserver_request_total{resource=\"sparkapplications\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "spark application API request",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(verb, code, resource) (rate(apiserver_request_total{resource=\"sparkapplications\"}[1m]))",
       "legendFormat": "{{verb}} - {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark Application Status at Locust Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "NEW (not yet submitted)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "locust_new_spark_application_gauge",
       "legendFormat": "NEW Job Count"
      }
     ]
    },
    {
     "title": "SUBMITTED",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 7 },
     "targets": [
      {
       "expr": "locust_submitted_spark_application_gauge",
       "legendFormat": "SUBMITTED Job Count"
      }
     ]
    },
    {
     "title": "RUNNING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "locust_running_spark_application_gauge",
       "legendFormat": "RUNNING Job Count"
      }
     ]
    },
    {
     "title": "SUCCEEDING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
     "targets": [
      {
       "expr": "locust_succeeding_spark_application_gauge",
       "legendFormat": "SUCCEEDING Job Count"
      }
     ]
    },
    {
     "title": "COMPLETED",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "locust_completed_spark_application_gauge",
       "legendFormat": "COMPLETED Job Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Node usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum Node CPU and Sum Allocable CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{resource = \"cpu\"})",
       "legendFormat": "Sum Node CPU"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource = \"cpu\"})",
       "legendFormat": "Sum Allocable CPU"
      }
     ]
    },
    {
     "title": "1 min cpu utilization by node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[1m]))*100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "max(apiserver_storage_objects{resource=\"nodes\"})",
       "legendFormat": "Node Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Locust metrics - Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locust Submit (success) Rate 1m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "increase(locust_spark_application_submit_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locust Submit Job Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_success_total{instance=\"ec2-instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Locust Submit (fail) Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(locust_spark_application_submit_fail_total{instance=\"ec2-instance\"}[1m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Locust Submit Job Fail Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_fail_total{instance=\"ec2-instance\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Locust Submit Job Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "locust_spark_application_submit_gauge{instance=\"ec2-instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Locust User Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 26 },
     "targets": [
      { "expr": "locust_concurrent_user", "legendFormat": "User Count" }
     ]
    }
   ]
  },
  {
   "title": "Spark Operator Metrics - Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "(operator) Failed Spark Job Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "increase(spark_app_failure_count [1m])",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "（operator) Failed Spark Job Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "targets": [
      { "expr": "sum(spark_app_failure_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "(operator) Averge Failure Job Run Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(spark_app_failure_execution_time_microseconds_sum [1m]) / rate(spark_app_failure_execution_time_microseconds_count [1m]) ",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "(operator) Success Spark Application Per Minutes",
     "type": "timeseries",
     "description": "Number of spark application change to SUCCEEDING state",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "\nrate(spark_app_success_count[1m])*60",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      },
      {
       "expr": "sum(rate(spark_app_success_count[1m])*60)",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "(operator) Success Spark Application Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "targets": [
      { "expr": "spark_app_success_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
      { "expr": "sum(spark_app_success_count)", "legendFormat": "sum" }
     ]
    },
    {
     "title": "(operator) Average Success Job Run Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(spark_app_success_execution_time_microseconds_sum [1m]) / rate(spark_app_success_execution_time_microseconds_count [1m])",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "(operator) Spark Application Count Increase Per Minute",
     "type": "timeseries",
     "description": "Number of newly added spark application",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
     "targets": [
      { "expr": "rate(spark_app_count[1m])*60", "legendFormat": "{{app_kubernetes_io_instance}}" },
      {
       "expr": "sum(rate(spark_app_count[1m])*60)",
       "legendFormat": "SUM"
      }
     ]
    },
    {
     "title": "(operator) Spark Application Count Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 27 },
     "targets": [
      { "expr": "spark_app_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
      { "expr": "sum(spark_app_count)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "(operator) Submit Spark Application Per Minute",
     "type": "timeseries",
     "description": "Number of spark application chnaged to SUBMITTED state",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "increase(spark_app_submit_count[1m])",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      },
      {
       "expr": "sum(increase(spark_app_submit_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(operator) Submitted Spark Application Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 35 },
     "targets": [
      { "expr": "spark_app_submit_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
      { "expr": "sum(spark_app_submit_count)", "legendFormat": "SUM" }
     ]
    },
    {
     "title": "(operator) Running Spark Application Count",
     "type": "timeseries",
     "description": "Number of spark application changed to RUNNING state",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
     "targets": [
      { "expr": "spark_app_running_count", "legendFormat": "{{app_kubernetes_io_instance}}" },
      { "expr": "sum(spark_app_running_count)", "legendFormat": "SUM" }
     ]
    },
    {
     "title": "Spark Operator Resident Memory Usage",
     "type": "timeseries",
     "description": "spark operator pod RSS memory",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{kubernetes_namespace=\"spark-operator\"} / 1024 ^ 3",
       "legendFormat": "{{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Spark Operator Pod CPU Core Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"spark-operator.*\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Spark Application Start Latency by 1H avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(spark_app_start_latency_microseconds_sum[60m])/rate(spark_app_start_latency_microseconds_count[60m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    },
    {
     "title": "Spark Application Start Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(spark_app_start_latency_microseconds_sum[5m])/rate(spark_app_start_latency_microseconds_count[5m])",
       "legendFormat": "{{app_kubernetes_io_name}}"
      }
     ]
    }
   ]
  }
 ]
}