apiVersion: locust.cloud/v1
kind: LocustTest
metadata:
  name: pvc-reuse-${CLUSTER_NAME}
  namespace: locust
spec:
  # image: locustio/locust:2.42.1
  image: ${ECR_URL}/locust:latest
  imagePullPolicy: IfNotPresent
  workers: 2
  # run locust-provision.sh to replaces env variables
  # or manually change by actual values
  env:
  - name: AWS_REGION
    value: ${REGION}
  - name: CLUSTER_NAME
    value: ${CLUSTER_NAME}
  - name: JOB_SCRIPT_NAME
    value: ${JOB_SCRIPT_NAME}
  - name: SPARK_JOB_NS_NUM
    value: 5
  extraArgs:
    -f /home/locust/locustfile.py
    --run-time=120m
    --users=300
    --spawn-rate=15
    --skip-log-setup
  locustfile:
    configMap:
      name: emr-loadtest-locustfile
  master:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  worker:
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "8"
        memory: "8Gi"