apiVersion: locust.cloud/v1
kind: LocustTest
metadata:
  name: pvc-reuse-cluster-10
  namespace: locust
spec:
  # have to use a custom image due to additional dependencies
  # image: locustio/locust:2.42.1  
  image: 061698477416.dkr.ecr.us-west-2.amazonaws.com/locust:latest
  imagePullPolicy: IfNotPresent
  workers: 2
  env:
  - name: AWS_REGION
    value: us-west-2
  - name: CLUSTER_NAME
    value: load-test-cluster-10
  - name: METRICS_PORT
    value: "8000"  
  - name: JOB_SCRIPT_NAME
    value: emr-job-run.sh
  - name: SPARK_JOB_NS_NUM # number of namespaces/VCs per Locust worker
    value: "5"
  args:
    -f /home/locust/locustfile.py
    --job-azs '["us-west-2a","us-west-2b"]'
    --run-time=60m
    --users=300
    --spawn-rate=2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    --skip-log-setup
    --headless
  locustfile:
    configMap:
      name: emr-loadtest-locustfile
  master:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "2Gi"
  worker:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8000"
      prometheus.io/path: "/metrics"
    resources:
      requests:
        cpu: "4"
        memory: "2Gi"
      limits:
        cpu: "10"
        memory: "8Gi"