apiVersion: locust.cloud/v1
kind: LocustTest
metadata:
  name: csi-tuned-pvc-reuse-cluster-10
  namespace: locust
spec:
  # image: locustio/locust:2.42.1
  image: 061698477416.dkr.ecr.us-west-2.amazonaws.com/locust:latest
  imagePullPolicy: IfNotPresent
  workers: 2
  env:
  - name: AWS_REGION
    value: us-west-2
  - name: CLUSTER_NAME
    value: load-test-cluster-10
  - name: JOB_SCRIPT_NAME
    value: emr-job-run.sh
  - name: SPARK_JOB_NS_NUM # number of namespaces/VCs per locust worker
    value: "5"
  args:
    -f /home/locust/locustfile.py
    --job-azs '["us-west-2a","us-west-2b"]'
    --run-time=60m
    --users=120
    --spawn-rate=15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    --skip-log-setup
    --headless
  locustfile:
    configMap:
      name: emr-loadtest-locustfile
  master:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
  worker:
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "8"
        memory: "8Gi"