apiVersion: locust.cloud/v1
kind: LocustTest
metadata:
  name: pvc-reuse-load-test-cluster-10
  namespace: locust
spec:
  # image: locustio/locust:2.42.1
  image: 061698477416.dkr.ecr.us-west-2.amazonaws.com/locust:latest
  imagePullPolicy: Always
  workers: 2
  env:
  - name: AWS_REGION
    value: us-west-2
  - name: CLUSTER_NAME
    value: load-test-cluster-10
  - name: JOB_SCRIPT_NAME
    value: emr-job-run.sh
  - name: SPARK_JOB_NS_NUM
    value: "2"
  # - name: LOCUST_SKIP_MONKEY_PATCH
  #   value: "1"
  args:
    -f /home/locust/locustfile.py
    --run-time=60m
    --users=120
    --spawn-rate=2
    --skip-log-setup
  locustfile:
    configMap:
      name: emr-loadtest-locustfile
  master:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
  worker:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"