---
apiVersion: v1
kind: Namespace
metadata:
  name: {spark_ns}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {spark_sa}
  namespace: {spark_ns}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {spark_role}
  namespace: {spark_ns}
rules:
  - apiGroups: ["*"]
    resources: ["configmaps","serviceaccounts","events","pods","pods/exec","pods/log","pods/portforward","secrets","services","persistentvolumeclaims"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {spark_rb}
  namespace: {spark_ns}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {spark_role}
subjects:
  - kind: ServiceAccount
    name: {spark_sa}
    namespace: {spark_ns}