apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: driver-nodepool
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmpty
  limits:
    cpu: "1000"
    # memory: 1000Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: memoryec2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64","arm64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]   
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - large
        - xlarge
        - 2xlarge
        - 4xlarge
        - 8xlarge
        - 12xlarge
        - 16xlarge
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["m", "c"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["4"]
