apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: driver-nodepool
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmpty
  limits:
    # Upto 8 nodes and 60 Drivers/Jobs for the lab purpose
    cpu: "128"
  template:
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: memoryec2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64","arm64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]   # to support prefix delegation
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - 4xlarge
        - 8xlarge
        - 9xlarge
        - 12xlarge
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["m", "c"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["4"]