apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: executor-memorynodepool
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    # Upto 215 nodes and 1700 Executor pods for the lab purpose
    cpu: "3440"
    # memory: 10420Gi
  template:
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: memoryec2
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64", "arm64"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]    # to support prefix delegation
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - 4xlarge
        - 8xlarge
        - 9xlarge
        - 12xlarge
        - 16xlarge
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["m", "c"]
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["4"]
