apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: memoryec2
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: "${KARPENTER_NODE_ROLE}"
  amiSelectorTerms:
    - alias: "al2023@v20251217"
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 50Gi
      volumeType: gp3
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  tags:
    Name: ${CLUSTER_NAME}-karpenter-node